coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    # https://docs.codecov.com/docs/commit-status#patch-status
    patch:
      default:
        target: 60%
        informational: false
        if_ci_failed: error

# https://docs.codecov.com/docs/pull-request-comments#disable-comment
comment: false

# https://docs.codecov.com/docs/ignoring-paths
ignore:
  - "../config"
  - "../docs"
  - "../examples"
  - "../hack"
  - "../pkg/apis"
  - "../test"
  - "../.github"
  - "*_test.go"
